/etc/resolvconf/resolv.conf.d/base（这个文件默认是空的）

在里面插入：
nameserver 8.8.8.8
nameserver 8.8.4.4

如果有多个DNS就一行一个

修改好保存，然后执行

resolvconf -u

再看/etc/resolv.conf，最下面就多了2行：

cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 8.8.4.4


ubuntu可以直接在interfaces 文件里面插入  
dns-nameserver 8.8.8.8  重启网络，就可以cat /etc/resolv.conf看到